### ISSUE TITLE
Do not run in Ubuntu.

### ISSUE THREAD

**Issue by rafaelstz** [JoshLankford/WakaTimeCLI#10]
I test in OSX and Ubuntu, and do not run on Ubuntu.

**Comment by Pautomagi** [comment]
Could you elaborate @rafaelstz ?
I have this running in three different ubuntu enviroments and working fine.
(14.04, 15.04, 15.10)

**Comment by rafaelstz** [comment]
Is issue is old, is now running, thank you!

**Comment by Pautomagi** [comment]
Look at that. Sorry for reviving this one then :)
