### ISSUE TITLE
Wrong logic for weekly report.

### ISSUE THREAD

**Issue by ucay** [JoshLankford/WakaTimeCLI#7]
When I try to get wakatime weekly report in February 2nd, I got an error.
It's because the logic of date is (today - 6), so the result will be (-4)

``` javascript
var dd3 = dd-6;
```

Maybe need another library (e.g.  datejs) to set the date.
So, it could be easier to get report in a week, two week, a month, 2 days, etc.

**Comment by JoshLankford** [comment]
Great point. I will look into this and push an updated version.

**Comment by JoshLankford** [comment]
Updated.
